Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebRadioGroup("tripType").Select "oneway" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebRadioGroup("tripType")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("passCount").Select "3" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("passCount")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("fromPort").Select "New York" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("fromPort")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("fromDay").Select "17" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("fromDay")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("toPort").Select "Paris" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("toPort")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("toMonth").Select "October" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("toMonth")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebRadioGroup("servClass").Select "First" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebRadioGroup("servClass")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("airline").Select "Blue Skies Airlines" @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").WebList("airline")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").Image("findFlights").Click @@ hightlight id_;_Browser("Find a Flight: Mercury").Page("Find a Flight: Mercury").Image("findFlights")_;_script infofile_;_ZIP::ssf18.xml_;_
